"use client";
import { useState } from 'react';
import { KeyEditor,PasswordEditor,PlanManager } from './admin-editors';
import type { SavedPlan,AuditEvent } from '@/lib/admin-types';
import { Activity, ArrowUpRight, Check, CircleAlert, CreditCard, KeyRound, LayoutDashboard, LoaderCircle, LogOut, RefreshCw, Settings2, ShieldCheck, Sprout, Users } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { Empty,EmptyHeader,EmptyMedia,EmptyTitle,EmptyDescription } from '@/components/ui/empty';

type Props={email:string;configured:boolean;vaultReady:boolean;plans:SavedPlan[];events:AuditEvent[]};
const sections=[{id:'overview',label:'Overview',icon:LayoutDashboard},{id:'service',label:'AI service',icon:Settings2},{id:'access',label:'Users & access',icon:Users},{id:'subscriptions',label:'Subscriptions',icon:CreditCard},{id:'usage',label:'Usage & limits',icon:Activity}];
export function AdminDashboard({email,configured:initialConfigured,vaultReady,plans,events}:Props) {
  const [configured,setConfigured]=useState(initialConfigured);
  const [tab,setTab]=useState('overview'),[busy,setBusy]=useState(false),[result,setResult]=useState<{ok:boolean;message:string}|null>(null);
  async function checkConnection(){
    setBusy(true);setResult(null);
    try{
      const response=await fetch('/api/admin/connection',{method:'POST',signal:AbortSignal.timeout(15_000)});
      const data=await response.json() as {ok:boolean;message?:string;error?:string};
      setResult({ok:response.ok&&data.ok,message:data.message??data.error??'The connection check could not complete.'});
    }catch{setResult({ok:false,message:'The connection check timed out or could not reach the app. Please try again.'});}
    finally{setBusy(false);}
  }
  return <Tabs value={tab} onValueChange={setTab} className="admin-shell">
    <aside className="admin-sidebar"><a className="admin-brand" href="/"><span><Sprout size={23}/></span>nutrilens.</a><div className="admin-workspace-label">ADMIN WORKSPACE</div><TabsList aria-label="Admin sections" className="admin-tabs">{sections.map(section=><TabsTrigger key={section.id} value={section.id}><section.icon size={19}/>{section.label}</TabsTrigger>)}</TabsList><div className="admin-sidebar-bottom"><ShieldCheck size={22}/><strong>Restricted workspace</strong><p>Access is checked on the server for your signed-in account.</p><a href="/">Open meal studio <ArrowUpRight size={15}/></a></div></aside>
    <div className="admin-content"><header className="admin-header"><span><ShieldCheck size={16}/>Administrator</span><div><a href="/">Meal studio <ArrowUpRight size={15}/></a><button className="admin-signout" onClick={async()=>{const response=await fetch("/api/admin/auth/logout",{method:"POST"});if(response.ok)window.location.assign("/admin");else setResult({ok:false,message:"Could not sign out. Please try again."});}}><LogOut size={15}/>Sign out</button></div></header>
    <main className="admin-main"><div className="admin-title"><div><span className="admin-kicker">NUTRILENS CONTROL ROOM</span><h1>{sections.find(section=>section.id===tab)?.label}</h1><p>Your service, its access, and the next steps toward launch.</p></div><button className="admin-secondary" onClick={()=>window.location.reload()}><RefreshCw size={16}/>Refresh status</button></div>

    <TabsContent value="overview"><div className="admin-stats"><Status label="Photo analysis" value={configured?'Key configured':'Setup needed'} note={configured?'Connection not yet verified':'Add the server credential'} good={configured}/><Status label="Admin access" value="Password protected" note="Revocable server sessions" good/><Status label="Subscriptions" value={`${plans.length} saved plans`} note="Hidden · no payments enabled"/><Status label="Usage tracking" value="Limits enforced" note="20 attempts/account per 24h"/></div>
    <div className="admin-grid"><article className="admin-card admin-launch"><div className="admin-card-icon"><Settings2 size={24}/></div><span className="admin-kicker">SERVICE READINESS</span><h2>{configured?'Check your AI connection.':'Connect the engine behind the experience.'}</h2><p>Customers use the meal studio. Save provider credentials securely here. Prepare subscription plans privately while the customer experience remains unchanged.</p><button className="admin-primary" onClick={()=>setTab('service')}>Review AI service <ArrowUpRight size={16}/></button></article><article className="admin-card"><h2>Launch checklist</h2><ul className="admin-checklist"><li><Check size={18}/><div><strong>Protect administrator access</strong><span>Email/password login with expiring, revocable sessions.</span></div></li><li>{configured?<Check size={18}/>:<CircleAlert size={18}/>}<div><strong>Configure photo analysis</strong><span>{configured?'Server credential present; test its connection.':'Save your Gemini credential in the AI service tab.'}</span></div></li><li><CircleAlert size={18}/><div><strong>Connect billing and entitlements</strong><span>Required before offering paid subscriptions.</span></div></li><li><CircleAlert size={18}/><div><strong>Track usage and enforce limits</strong><span>Durable attempt limits are active. Paid entitlements are not enabled.</span></div></li></ul></article></div></TabsContent>
    <TabsContent value="service"><article className="admin-card"><div className="admin-card-heading"><div><span className="admin-kicker">PHOTO ANALYSIS</span><h2>AI service configuration</h2></div><span className={`admin-badge ${configured?'ready':''}`}>{configured?'Configured':'Setup needed'}</span></div><dl className="admin-facts"><div><dt>Provider</dt><dd>Google Gemini</dd></div><div><dt>Model</dt><dd>Gemini 3.5 Flash-Lite</dd></div><div><dt>Credential</dt><dd>{configured?'Encrypted storage / server secret · value hidden':'Not configured'}</dd></div><div><dt>Customer access</dt><dd>Signed-in customer or authenticated admin</dd></div></dl><div className="admin-service-actions"><button disabled={!configured||busy} className="admin-primary" onClick={()=>void checkConnection()}>{busy?<LoaderCircle size={16} className="spin"/>:<Activity size={16}/>} {busy?'Checking connection…':'Test AI generation'}</button><p>Sends a small text-only generation test using your saved key. It uses a small amount of API quota; no meal photo is uploaded.</p></div>{result&&<div role="status" className={`admin-test-result ${result.ok?'success':''}`}>{result.ok?<Check size={18}/>:<CircleAlert size={18}/>}<p>{result.message}</p></div>}</article>
    <div className="admin-grid admin-section-gap"><article className="admin-card"><KeyRound size={24}/><h2>Add or replace the API key</h2><p>The key is encrypted before it is saved. You can replace it here without changing application code.</p><KeyEditor ready={vaultReady} onSaved={()=>setConfigured(true)}/><a className="admin-secondary" href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">Open Google AI Studio <ArrowUpRight size={15}/></a></article><article className="admin-card"><ShieldCheck size={24}/><h2>Private service credentials</h2><p>Saved keys cannot be revealed through this dashboard. Customers never see the key, and browser-supplied keys are rejected by the analysis endpoint.</p><p>The encryption key stays outside the database in the hosting secrets. Back it up securely before changing environments.</p></article></div></TabsContent>
    <TabsContent value="access"><div className="admin-grid"><article className="admin-card"><span className="admin-kicker">OWNER ACCOUNT</span><h2>Administrator access</h2><dl className="admin-facts"><div><dt>Email</dt><dd>{email}</dd></div><div><dt>Authentication</dt><dd>Email and password</dd></div><div><dt>Session lifetime</dt><dd>8 hours maximum</dd></div><div><dt>Inactivity timeout</dt><dd>30 minutes</dd></div></dl><p>There is no public admin registration. Setup is locked after the owner account is created.</p><p>Changing the password invalidates every existing admin session.</p></article><article className="admin-card"><h2>Change password</h2><PasswordEditor/></article></div></TabsContent>
    <TabsContent value="subscriptions"><PlanManager initialPlans={plans}/></TabsContent>
    <TabsContent value="usage"><div className="admin-grid"><article className="admin-card"><h2>Analysis safeguards</h2><dl className="admin-facts"><div><dt>Account allowance</dt><dd>20 attempts / 24-hour window</dd></div><div><dt>Service allowance</dt><dd>100 attempts / 24-hour window</dd></div><div><dt>Provider timeout</dt><dd>55 seconds</dd></div><div><dt>Paid entitlement checks</dt><dd>Not active</dd></div></dl><p>Attempt limits are reserved on the server before calling the provider. These are service safeguards, separate from the draft plan allowances.</p></article><article className="admin-card"><h2>Billing stays private</h2><p>Saved plans are visible to administrators only. There is no customer pricing page, purchase endpoint, payment collection, or automatic subscription activation.</p><p>Payment-provider configuration and verified billing events are required before paid access can launch.</p></article></div><article className="admin-card admin-section-gap"><h2>Recent admin activity</h2><p>Successful administrative actions from the last 90 days. Passwords and API keys are never included.</p>{events.length?<Table><TableHeader><TableRow><TableHead>Action</TableHead><TableHead>Time (UTC)</TableHead></TableRow></TableHeader><TableBody>{events.map(event=><TableRow key={event.id}><TableCell>{event.action.replaceAll('_',' ')}</TableCell><TableCell>{new Date(event.created_at).toISOString().replace('T',' ').slice(0,19)}</TableCell></TableRow>)}</TableBody></Table>:<p>No activity recorded yet.</p>}</article></TabsContent>
    <div className="admin-session"><ShieldCheck size={14}/><span>Signed in as {email}</span><span>Credentials remain hidden</span></div></main></div>
  </Tabs>;
}
function Status({label,value,note,good=false}:{label:string;value:string;note:string;good?:boolean}){return <article className="admin-stat"><span>{label}</span><strong className={good?'good':''}>{value}</strong><small>{note}</small></article>;}
