"use client";
import { useState } from 'react';
import { ShieldCheck,Sprout,LoaderCircle } from 'lucide-react';
import { Input } from '@/components/ui/input';
export function AdminLogin({setup=false,available=true}:{setup?:boolean;available?:boolean}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[setupToken,setToken]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checking,setChecking]=useState(false),[verified,setVerified]=useState(false);
 const cleanToken=()=>setupToken.replace(/^\s*One-time setup token:\s*/i,'').trim();
 async function verifyToken(){setError('');setVerified(false);setChecking(true);try{const response=await fetch('/api/admin/auth/setup-check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({setupToken:cleanToken()})});const result=await response.json() as {email?:string;error?:string};if(!response.ok||!result.email)throw new Error(result.error??'Could not verify the setup token.');setEmail(result.email);setToken(cleanToken());setVerified(true);}catch(e){setError((e as Error).message);}finally{setChecking(false);}}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(setup&&password!==confirm){setError('The passwords do not match.');return;}setBusy(true);try{const response=await fetch('/api/admin/auth/'+(setup?'setup':'login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,...(setup?{setupToken:cleanToken()}: {})})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error??'Could not sign in.');setPassword('');setConfirm('');setToken('');window.location.assign(setup?'/admin?created=1':'/admin');}catch(e){setError(e instanceof Error?e.message:'The request could not complete.');}finally{setBusy(false);}}
 return <main className="admin-gate"><a className="admin-brand" href="/"><span><Sprout size={23}/></span>nutrilens.</a><ShieldCheck size={36}/><h1>{setup?'Create your admin password.':'Welcome back, admin.'}</h1><p>{setup?'One-time account setup for the authorized owner. Choose a password you do not use elsewhere.':'Sign in with your administrator email and password.'}</p>{!available?<p role="status">Admin storage is being configured. Please try again shortly.</p>:<form onSubmit={submit} className="admin-form"><label htmlFor="admin-email">Email</label><Input id="admin-email" type="email" autoComplete="username" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/>{setup&&<><label htmlFor="setup-token">One-time setup token</label><Input id="setup-token" type="password" autoComplete="off" required value={setupToken} onChange={e=>{setToken(e.target.value);setVerified(false);}} maxLength={128} placeholder="Paste the token from your private setup file"/><small>Copy the token from the private setup file. Verify it to automatically fill in the authorized owner email.</small><button className="admin-secondary" type="button" disabled={checking||busy||!setupToken.trim()} onClick={()=>void verifyToken()}>{checking?"Verifying…":"Verify setup token"}</button>{verified&&<p className="admin-form-success" role="status">Token verified. The authorized email has been filled in.</p>}</>}<label htmlFor="admin-password">{setup?'New password':'Password'}</label><Input id="admin-password" type="password" autoComplete={setup?'new-password':'current-password'} required minLength={setup?15:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/>{setup&&<><small>Use 15–128 characters. A long, unique passphrase works well.</small><label htmlFor="admin-confirm">Confirm password</label><Input id="admin-confirm" type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></>}{error&&<p className="admin-form-error" role="alert">{error}</p>}<button disabled={busy} className="admin-primary" type="submit">{busy&&<LoaderCircle size={16} className="spin"/>}{busy?'Please wait…':setup?'Create admin account':'Sign in'}</button></form>}<a className="admin-secondary" href={setup?'/admin':'/'}>{setup?'Back to sign in':'Return to meal studio'}</a>{!setup&&<small>First visit? <a href="/admin/setup">Set up the owner account</a>. If you lose your password, use the private owner recovery procedure.</small>}</main>;
}
